// Generated by jextract

package org.breizhjug.jdk21.panama.libzstd;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$11 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$11() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ZSTD_createDStream",
        constants$0.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ZSTD_freeDStream",
        constants$3.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ZSTD_initDStream",
        constants$3.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ZSTD_decompressStream",
        constants$10.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ZSTD_DStreamInSize",
        constants$9.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ZSTD_DStreamOutSize",
        constants$9.const$3
    );
}


