// Generated by jextract

package org.breizhjug.jdk21.panama.libzstd;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$8 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$8() {}
    static final VarHandle const$0 = constants$7.const$3.varHandle(MemoryLayout.PathElement.groupElement("pos"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("dst"),
        JAVA_LONG.withName("size"),
        JAVA_LONG.withName("pos")
    ).withName("ZSTD_outBuffer_s");
    static final VarHandle const$2 = constants$8.const$1.varHandle(MemoryLayout.PathElement.groupElement("dst"));
    static final VarHandle const$3 = constants$8.const$1.varHandle(MemoryLayout.PathElement.groupElement("size"));
    static final VarHandle const$4 = constants$8.const$1.varHandle(MemoryLayout.PathElement.groupElement("pos"));
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ZSTD_createCStream",
        constants$0.const$2
    );
}


