// Generated by jextract

package org.breizhjug.jdk21.panama.libzstd;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$17 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$17() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ZSTD_sizeof_CDict",
        constants$3.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ZSTD_sizeof_DDict",
        constants$3.const$4
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ZDICT_trainFromBuffer",
        constants$17.const$2
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("compressionLevel"),
        JAVA_INT.withName("notificationLevel"),
        JAVA_INT.withName("dictID")
    ).withName("");
    static final VarHandle const$5 = constants$17.const$4.varHandle(MemoryLayout.PathElement.groupElement("compressionLevel"));
}


