// Generated by jextract

package org.breizhjug.jdk21.panama.libzstd;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$16 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$16() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ZSTD_DCtx_refDDict",
        constants$10.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ZSTD_DCtx_refPrefix",
        constants$15.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ZSTD_sizeof_CCtx",
        constants$3.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ZSTD_sizeof_DCtx",
        constants$3.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ZSTD_sizeof_CStream",
        constants$3.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ZSTD_sizeof_DStream",
        constants$3.const$4
    );
}


