// Generated by jextract

package org.breizhjug.jdk21.panama.libzstd;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$15 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$15() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ZSTD_getDictID_fromFrame",
        constants$14.const$1
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ZSTD_CCtx_loadDictionary",
        constants$15.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ZSTD_CCtx_refCDict",
        constants$10.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ZSTD_CCtx_refPrefix",
        constants$15.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ZSTD_DCtx_loadDictionary",
        constants$15.const$1
    );
}


