// Generated by jextract

package org.breizhjug.jdk21.panama.libzstd;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$5 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$5() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_LONG.withName("error"),
        JAVA_INT.withName("lowerBound"),
        JAVA_INT.withName("upperBound")
    ).withName("");
    static final VarHandle const$1 = constants$5.const$0.varHandle(MemoryLayout.PathElement.groupElement("error"));
    static final VarHandle const$2 = constants$5.const$0.varHandle(MemoryLayout.PathElement.groupElement("lowerBound"));
    static final VarHandle const$3 = constants$5.const$0.varHandle(MemoryLayout.PathElement.groupElement("upperBound"));
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_LONG.withName("error"),
        JAVA_INT.withName("lowerBound"),
        JAVA_INT.withName("upperBound")
    ).withName(""),
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ZSTD_cParam_getBounds",
        constants$5.const$4
    );
}


