// Generated by jextract

package org.breizhjug.jdk21.panama.libzstd;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     int compressionLevel;
 *     unsigned int notificationLevel;
 *     unsigned int dictID;
 * };
 * }
 */
public class ZDICT_params_t {

    public static MemoryLayout $LAYOUT() {
        return constants$17.const$4;
    }
    public static VarHandle compressionLevel$VH() {
        return constants$17.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int compressionLevel;
     * }
     */
    public static int compressionLevel$get(MemorySegment seg) {
        return (int)constants$17.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int compressionLevel;
     * }
     */
    public static void compressionLevel$set(MemorySegment seg, int x) {
        constants$17.const$5.set(seg, x);
    }
    public static int compressionLevel$get(MemorySegment seg, long index) {
        return (int)constants$17.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void compressionLevel$set(MemorySegment seg, long index, int x) {
        constants$17.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle notificationLevel$VH() {
        return constants$18.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int notificationLevel;
     * }
     */
    public static int notificationLevel$get(MemorySegment seg) {
        return (int)constants$18.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int notificationLevel;
     * }
     */
    public static void notificationLevel$set(MemorySegment seg, int x) {
        constants$18.const$0.set(seg, x);
    }
    public static int notificationLevel$get(MemorySegment seg, long index) {
        return (int)constants$18.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void notificationLevel$set(MemorySegment seg, long index, int x) {
        constants$18.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle dictID$VH() {
        return constants$18.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int dictID;
     * }
     */
    public static int dictID$get(MemorySegment seg) {
        return (int)constants$18.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int dictID;
     * }
     */
    public static void dictID$set(MemorySegment seg, int x) {
        constants$18.const$1.set(seg, x);
    }
    public static int dictID$get(MemorySegment seg, long index) {
        return (int)constants$18.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void dictID$set(MemorySegment seg, long index, int x) {
        constants$18.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


