// Generated by jextract

package org.breizhjug.jdk21.panama.libzstd;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct ZSTD_inBuffer_s ZSTD_inBuffer;
 * }
 */
public final class ZSTD_inBuffer extends ZSTD_inBuffer_s {

    // Suppresses default constructor, ensuring non-instantiability.
    private ZSTD_inBuffer() {}
}


